curso_flask/blueprints/app/models.py
from curso_flask.blueprints.app import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def current_user(user_id):
    return User.query.get(user_id)

books_in_user = db.Table(
    'books_users',
    db.Column('user_id', db.Integer,
    db.ForeignKey('users.id'), nullable=False),
db.Column('book_id', db.Integer,
    db.ForeignKey('books.id'), nullable=False)
    )

#UserMixin
class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(84), nullable=False)
    email = db.Column(db.String(84), nullable=False, unique=True, index=True)
    password = db.Column(db.String(255), nullable=False)
    profile = db.relationship('Profile', backref='user', uselist=False)
    books = db.relationship("Book", secondary=books_in_user, lazy=True, backref=db.backref('users'))

    def __str__(self):
        return self.name


class Profile(db.Model):
    __tablename__ = 'profiles'

    id = db.Column(db.Integer(), primary_key=True)
    photo = db.Column(db.Unicode(124), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))


class Book(db.Model):
    __tablename__ = 'books'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(125), nullable=False)
    

    def __str__(self):
        return self.name

curso_flask/blueprints/app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SelectField, StringField, PasswordField, BooleanField, SubmitField, EmailField
from wtforms.validators import length, email,DataRequired

from curso_flask.blueprints.app.models import Book

class LoginForm(FlaskForm):
    email = EmailField('email')
    password = PasswordField('senha')
    remember = BooleanField('permanecer conectado')
    submit = SubmitField('logar')


class RegisterForm(FlaskForm):
    name = StringField('nome completo', validators=[DataRequired('campo obrigatorio')])
    email = EmailField('email', validators=[email(), DataRequired('campo obrigatorio')])
    password = PasswordField('senha',validators=[DataRequired('campo obrigatorio'),length(3,12, 'range de 3 a 12 caractere')])
    submit = SubmitField('cadastrar')


class BookForm(FlaskForm):
    name = StringField('nome do livro', validators=[DataRequired('campo obrigatorio')])
    submit = SubmitField('salvar')


class UserBookForm(FlaskForm):
    book = SelectField('livro', coerce=int,)
    submit = SubmitField('salvar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.book.choices= [(book.id, book.name) for book in Book.query.all()]

curso_flask/blueprints/app/__init__.py
from datetime import timedelta

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap4

db = SQLAlchemy()
login_manager = LoginManager()
bootstrap = Bootstrap4()

class DefaultConfig:
    SECRET_KEY = 'default-secret-key'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///./database.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    TEMPLATES_AUTO_RELOAD = True


def create_app(config_class=None):
    app = Flask(__name__)
    # app.config['SECRET_KEY'] = 'secret'
    # app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///./database.db'
    # app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    # app.config['TEMPLATES_AUTO_RELOAD'] = True

    if config_class:
        app.config.from_object(config_class)
    else:
        app.config.from_object(DefaultConfig)

    login_manager.init_app(app)
    db.init_app(app)
    bootstrap.init_app(app)

    from curso_flask.blueprints.app import routers

    routers.init_app(app)

    return app

curso_flask/blueprints/app/book/__init__.py
from flask import Blueprint

book = Blueprint('book', __name__)

from curso_flask.blueprints.app.book import views

curso_flask/blueprints/app/book/views.py
from flask import render_template, redirect, url_for, flash
from flask_login import  current_user

from curso_flask.blueprints.app.models import  Book
from curso_flask.blueprints.app import db
from curso_flask.blueprints.app.forms import  BookForm, UserBookForm
from curso_flask.blueprints.app.book import book


@book.route('/book/add/', methods=['GET', 'POST'])
def book_add():
    form = BookForm()

    if form.validate_on_submit():
        book = Book()
        book.name = form.name.data

        db.session.add(book)
        db.session.commit()

        flash('Livro cadastrado com sucesso', 'success')
        return redirect(url_for('.book_add'))

    return render_template('book/add.html', form=form)

@book.route('/user/<int:id>/add-book', methods=['GET', 'POST'])
def user_add_book(id):
    form = UserBookForm()
    if form.validate_on_submit():
        book = Book.query.get(form.book.data)
        current_user.books.append(book)

        db.session.add(current_user)
        db.session.commit()

        flash('Livro cadastrado com sucesso', 'success')
        return redirect(url_for('.user_add_book', id=id))

    return render_template('book/user_add_book.html',form=form)

curso_flask/blueprints/app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from curso_flask.blueprints.app.users import views

curso_flask/blueprints/app/users/views.py
from flask import render_template, redirect, url_for
from flask_login import  login_required

from curso_flask.blueprints.app.models import User
from curso_flask.blueprints.app import db
from curso_flask.blueprints.app.users import users


@users.route('/')
def index():
    users = User.query.all()
    return render_template('users.html', users=users)

@users.route('/user/<int:id>')
@login_required
def detail(id):
    user = User.query.get(id)
    return render_template('user.html', user=user)


@users.route('/user/delete/<int:id>')
def delete(id):
    user = User.query.filter_by(id=id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('index'))

curso_flask/blueprints/app/templates/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% block styles %}
      {{bootstrap.load_css()}}
    {% endblock styles %} 
   

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>

    
    <div class="container">
      {% block content %} {% endblock content %}
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    {% block scripts %}
      {{bootstrap.load_js()}}
    {% endblock scripts %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

curso_flask/blueprints/app/templates/book/add.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block content %}
    {% include "nav.html" %}
    {% include "components/notification.html" %}

    {{ render_form(form)}}

{% endblock content %}

curso_flask/blueprints/app/templates/book/user_add_book.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block content %}
    {% include "nav.html" %}
    {% include "components/notification.html" %}

    {{ render_form(form)}}

{% endblock content %}

curso_flask/blueprints/app/templates/components/notification.html
{% with messages = get_flashed_messages(with_categories=True) %}
  {% if messages %}
      {% for category ,message in messages %}
        <div class="alert alert-{{category}} text-center">
          {{message}}
        </div>     
      {% endfor %}
  {% endif %}
{% endwith %}

curso_flask/blueprints/app/templates/login.html
{% extends "base.html" %}


{% block content %}
{% from 'bootstrap/form.html' import render_form %}

{% include "components/notification.html" %}

{% if form.errors %}
  {% for error in form.errors %}
    <div class="alert alert-danger ">
      {{error}}
    </div>
  {% endfor %}
{% endif %}


  {{ render_form(form )}}



<!--

<form action="{{ url_for('auth.login') }}" method='POST'>

  {{ form.csrf_token }}
  
  <div class="form-group">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      {{form.email(class="form-control", id="inputEmail4")}}
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Password</label>
      {{form.password(class="form-control", id="inputPassword4")}}
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-2">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
    <div class="form-check form-check-inline">
  
    {{form.remember(class="form-check-input", id="inlineCheckbox1")}}
  <label class="form-check-label" for="inlineCheckbox1">remember</label>
</div>
     
    </div>
  </div>
    {{form.submit(class="btn btn-primary")}}
</form> -->


{% endblock content %} 

curso_flask/blueprints/app/templates/nav.html
 <nav>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <h1><a class="nav-link" href="{{url_for('users.index')}}">Users</a></h1>
        </li>
    {% if not current_user.is_authenticated %}
        
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.register')}}">register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.login')}}">login</a>
        </li>

    {% else %}

        <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.logout')}}">logout</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('book.book_add')}}">add book</a>
        </li>
        </ul>
    {% endif %}
</nav>

           
    

curso_flask/blueprints/app/templates/register.html
{% extends "base.html" %}

{% block content %}
{% from 'bootstrap/form.html' import render_form %}
{% include "nav.html" %}

 
  {{render_form(form)}}
 

<!--
<form action="{{ url_for('auth.register') }}" method='POST'>
  <div class="form-group"></div>
  <div class="form-group">
    <label for="inputAddress">Name</label>
    <input type="text" class="form-control" id="inputAddress" placeholder=" Alex silva ..." name="name">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" name="email">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Password</label>
      <input type="password" class="form-control" id="inputPassword4" name="password">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-2">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
     
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>  
-->


{% endblock content %}

curso_flask/blueprints/app/templates/user.html
{% extends "base.html" %}

{% block content %}

<h1>Usuario</h1>
<div class="mt-4 mb-4">
    <a href="{{url_for('book.user_add_book', id=user.id)}}" class="btn btn-success"> adicionar livro </a>
</div>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">{{user.id}} </li>
        <li class="list-group-item">{{ user.name}}</li>
        <li class="list-group-item">{{user.email}}</li>
        <li class="list-group-item">{{user.profile.photo}}</li>
    </ul>
    <h2>Livros</h2>

    <ul class="list-group list-group-flush">
        {% for book in user.books %}
        <li class="list-group-item">{{book.name}} </li>
        {% endfor %}
    </ul>


        <br>
            <a href="{{url_for('users.delete', id=user.id)}}" class="btn btn-warning"> deletar </a>
        <br>
   

{% endblock content %}

curso_flask/blueprints/app/templates/users.html
{% extends "base.html" %}

{% block title %}
    users
{% endblock title %}

{% block content %}

    {% include "nav.html" %}

   
    {% for user in users %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a href="{{url_for('users.detail', id=user.id)}}">{{ user.name }}</a>
            </li>
        </ul>
    {% endfor %}


{% endblock content %}

    
    